name: lOGIN Images

on: 
  push:
    branches:
      - dev

permissions:
  id-token: write
  contents: read

env:
  AZURE_REGION: 'eastus'
  ACR_NAME: 'devopscontRegistry'
  RESOURCE_GROUP_NAME: 'myResourceGroup'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    timeout-minutes: 60  
    strategy:
      matrix:
        service:
          - src/shoppingassistantservice
    outputs:
      images: ${{ steps.set-images-output.outputs.images }} 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Verify Azure CLI installation
        run: |
          az --version

      - name: Log in to Azure
        uses: azure/login@v1.4.7
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          

      - name: Log in to Azure Container Registry
        run: |
          az acr login --name ${{ env.ACR_NAME }}

      

      - id: set-images-output 
        run: echo "images=$(echo ${{ matrix.service }} | sed 's/src\///g' | sed 's/\/src//g')" >> $GITHUB_OUTPUT

      - name: Azure CLI logout
        run: |
          az logout
