name: lOGIN Images

on: 
  push:
    branches:
      - dev

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    timeout-minutes: 60  
    steps:
      - name: Log in to Azure
        uses: azure/login@v1.4.7
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure CLI logout
        run: |
          az logout
